				create table types(                                                                 id int unsigned not null primary key auto_increment,                            name varchar(50),                                                               inactive char(1)                                                             )engine=InnoDB ;

				 insert into types values(0,'General',null),(0,'Water',null),(0,'Sewer',null),(0,'Stormwater',null),(0,'Electric',null),(0,'Carpentry',null),(0,'Maintenance',null),(0,'Emergency',null),(0,'Other',null);
				
				 create table groups(                                                              id int unsigned not null primary key auto_increment,                            name varchar(50),                                                               inactive char(1),                                                               index(name)                                                                     )engine=InnoDB;

				 	create table departments(                                                            id int unsigned not null primary key auto_increment,                            name varchar(50) not null,                                                      inactive char(1)                                                           )engine=InnoDB; 

				create table divisions(                                                              id int unsigned not null primary key auto_increment,                            name varchar(50) not null,                                                      inactive char(1),                                                               dept_id int unsigned,                                                           foreign key(dept_id) references departments(id)                             )engine=InnoDB ;

				create table users (                                                               id int unsigned not null auto_increment primary key,                             username varchar(9) not null,                                                   fullname varchar(50),                                                           role enum('Super','Admin','Delete:Edit','Edit','View'),                         dept_id int unsigned,                                                           division_id int unsigned,                                                       inactive char(1),                                                               foreign key(dept_id) references departments(id),                                foreign key(division_id) references divisions(id)                               )engine=InnoDB;

				create table group_users(                                                           id int unsigned not null auto_increment primary key,                            group_id int unsigned not null,                                                 user_id  int unsigned not null,                                                 unique(group_id,user_id),                                                       foreign key(group_id) references groups(id),                                    foreign key(user_id) references users(id)                                      )engine=InnoDB;

				create table requests (                                                          id int unsigned primary key auto_increment,                                     type_id int unsigned,                                                           status enum('Unassigned','Active','Closed','Cancelled'),                        date datetime,                                                                  username varchar(8),                                                            fullname varchar(50),                                                           phone varchar(20),                                                              dept varchar(50),                                                               division varchar(50),                                                           group_id int unsigned,                                                          location varchar(250),                                                          summary varchar(100),                                                           description varchar(1024),                                                      due_date date,                                                                  foreign key(type_id) references types(id),						                           foreign key(group_id) references groups(id),                                    index(summary),                                                                 index(description(100)),                                                        index(status),                                                                  index(date),                                                                    index(due_date),                                                                index(dept),                                                                    index(division)                                                                )engine=InnoDB;

								create table tasks(                                                              id int unsigned not null primary key auto_increment,                            request_id int unsigned,                                                        name varchar(80),                                                               date date,                                                                      task_by int unsigned,                                                           completed enum('0','25','50','75','100'),                                       notes varchar(500),                                                             hours double(5,2) default 0,                                                    expenses double(5,2) default 0,                                                 foreign key(request_id) references requests(id),                                foreign key(task_by) references users(id),                                      index(date),                                                                    index(notes(100))                                                              )engine=InnoDB ;

				
   			 create table assignments(                                                          id int unsigned not null primary key auto_increment,                            user_id int unsigned,                                                           request_id int unsigned,                                                        date date,                                                                      foreign key(user_id) references users(id),                                      foreign key(request_id) references requests(id)                               )engine=InnoDB ;				

				 create table request_logs(                                                       id int unsigned not null primary key auto_increment,                            request_id int unsigned not null,                                               user_id  int unsigned not null,                                                 date datetime,                                                                  type enum('Created','Updated','Closed','Cancelled','Reopen'),                   notes varchar(512),                                                             foreign key(request_id) references requests(id),                                foreign key(user_id) references users(id)                                       )engine=InnoDB;
